# Get vocab from transcription

## Create nocabulary from transcription

In [2]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

from util import *


In [7]:
full_ids = []
with open('./data/processed/IEMOCAP/processed_ids.txt') as f:
    full_ids = f.readlines()
full_ids = [x.strip() for x in full_ids]


In [8]:
print(full_ids[:10])

['Ses01F_impro01_F000', 'Ses01F_impro01_F001', 'Ses01F_impro01_F002', 'Ses01F_impro01_F005', 'Ses01F_impro01_F012', 'Ses01F_impro01_F014', 'Ses01F_impro01_M011', 'Ses01F_impro01_M013', 'Ses01F_impro02_F000', 'Ses01F_impro02_F001']


In [9]:
print(len(full_ids))

5531


In [10]:
sentences = []
for line in csv_reader('./data/processed/IEMOCAP/processed_tran.csv'):
    file_line = line.strip().split(',')

    for idx, file_id in enumerate(full_ids):
        if line != '\n' and (file_id == file_line[0]):
            sentences.append(file_line[1])
            del full_ids[idx]
            break


In [19]:
print(len(sentences))

5531


In [12]:
print(sentences[-1])

You're a wicked little vampire.  And I pray to God I never set eyes on you again as long as I live.


In [13]:
tokenizer = Tokenizer(oov_token='<oov>')
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index

sequences = tokenizer.texts_to_sequences(sentences)
padded = pad_sequences(sequences, padding='post')


In [14]:
print('Number of words found -->', len(word_index))

Number of words found --> 2269


In [30]:
print('Padded Sequences:')
print(padded)

Padded Sequences:
[[ 779   27    0 ...    0    0    0]
 [  15    0    0 ...    0    0    0]
 [  19   57    7 ...    0    0    0]
 ...
 [ 294   23    0 ...    0    0    0]
 [  24  148    3 ...    0    0    0]
 [  37    7 1403 ...    0    0    0]]


In [31]:
print(padded.shape)

(5531, 98)


## Save Text sequences

In [33]:
np.save('D:/text_sequences.npy', padded)

In [3]:
padded = np.load('D:/text_sequences.npy')


In [4]:
padded

array([[ 779,   27,    0, ...,    0,    0,    0],
       [  15,    0,    0, ...,    0,    0,    0],
       [  19,   57,    7, ...,    0,    0,    0],
       ...,
       [ 294,   23,    0, ...,    0,    0,    0],
       [  24,  148,    3, ...,    0,    0,    0],
       [  37,    7, 1403, ...,    0,    0,    0]])

In [5]:
padded.shape

(5531, 98)